const en = {
    profile: {
        contact: "Contact",
        about: "About",
        badges: "Badges",
        editProfile: "Edit Profile",
        currentRank: "Current Rank",
        lockedBadges: "Locked Badges",
        email: "Email",
        personalEmail: "Personal Email",
        contactNumber: "Contact Number",
        facebook: "Facebook",
        linkedin: "Linkedin",
        skype: "Skype",
        uploadPhoto: "Upload Photo ",
        editProfilePic: "Edit Profile Picture",
        uploadProfilePic: " + Upload Profile Picture",
        max: "max",
        personalInfo: "Personal Information",
        nickname: "Nickname",
        bio: "Bio",
        phoneNumber: "Phone Number",
        fullName: 'Fullname',
        aboutMe: "About Me",
        profileUpdateMsg: "Profile Updated Successfully",
        profileImageUpdateMsg: "Profile Image Updated Successfully.",
        internalErr: "Something went wrong!",
        emailValid: "Email is valid.",
        emailInvalid: "Please enter a valid Email format. Eg. abc@selfdrvn.com",
        numberValid: "Number is valid.",
        numberInvalid: "Please use a valid contact number format. Eg.6012-3456789",
        emailNotString: "Email is not a string!",
        numberNotString: "Number is not a string!"
      },
      notifications: {
        notifications: "Notifications",
        all: 'All',
        important: 'Important',
        unread: "Unread",
        general: "General",
        markAllAsRead: "Mark All as Read",
        markAsRead: "Mark as Read",
        attention: 'Attention!',
        noNotificationMsg: "Looks like there's no notifications available yet"
      },
      groups: {
        details: "Details",
        assignAsAdmin: "Assign as admin",
        settings: "Settings",
        detailsHeader: "Please add details of your community",
        groupName: "Community Name",
        groupPhoto: "Community photo",
        selectPhoto: "Select a photo",
        groupTitlePlaceholder: "Please provide a name for your community",
        groupDescPlaceholder: "Tell us what this community is about",
        selectPrivacy: "Select privacy",
        privatePrivacyLabel: "Private - Only visible to you and the people you added",
        publicPrivacyLabel: "Public - Visible to everyone in this organisation",
        settingsHeader: "Select your community settings",
        onlyAdmin: "Only admin",
        anyoneInGroup: "Anyone in the community",
        create: "Create",
        loading: "Loading ...",
        noRecordsFound: "No Records Found",
        searchIndividual: "Search Individual",
        membersHeader: "Select members to add to community",
        imageWarningMessage: "This file format is not supported.",
        selectAll: "Select All",
        searchByTeam: "Search by Team",
        admin: "Admin",
        member:"Member",
        individual: "Individual",
        specificGroup: "Specific Group",
        groups: "Communities",
        createGroup: "Create Community",
        yourGroups:"Your communities",
        allGroups:"Public communities",
        search:"Search",
        sortBy:"Sort by:",
        noGroups:"Looks like there's no community available",
        noYourGroups:"Looks like you haven't joined any community yet, create or join one now!",
        joinedGroup:"Joined community",
        msg:'You have joined the community',
        cancel:"Cancel",
        recentlyUpdated:"Recently updated",
        recentlyCreated:"Recently created",
        join:"Join",
        private:"Private - Visible only to you and the community members",
        public:"Public - Visible to everyone",
        members:"Members",
        description:"Description",
        showMore:"Show more",
        showLess:"Show less",
        groupDescription:"Community description",
        allPosts:"All posts",
        pinnedPosts:"Pinned posts",
        muteAll:"Mute all",
        editGroup:"Edit community",
        leaveGroup:"Leave community",
        groupMember:"Community members",
        updatedSuccess:"Updated Successfully",
        createdOn:"Created",
        more:"more",
        removeAdmin:"Remove admin",
        makeAdmin:"Assign as admin",
        removeMember:"Remove member",
        becomeAdmin:"Become an admin",
        noAdmin:"There is no admin in this community",
        leaveGroupConfirmation:"Leave Community Confirmation",
        lastAdminMsg:"You are the last admin",
        assignAnAdminMessage:"Please assign an admin before leaving.",
        groupLastMemberMsg:"As the only member, this community will be deleted if you leave. Do you still want to leave?",
        nonAdminLeaveMsg:"Are you sure that you want to leave",
        adminLeaveMsg:"Are you sure that you want to give up your admin privileges and leave",
        memberAdded:"Member added to the community",
        addGroup:"Add to community",
        memberSuggestion:"Member suggestions",
        selectCommunity: "Select community",
        selectCommunityBeforePosting: "Please select your community before posting",
        allCommunities: "All communities",
        goToGroup: "Go to community",
        communityName: "Community Name",
        createdDate: "Created Date",
        type: "Type",
        searchGroups: "Search for communities",
        publicTxt: "Public",
        privateTxt: "Private",
        membersOf: "Members of",
        adminsOf: "Admins of",
        createdGroupOn: "Created the community on",
        addedOn: "Added on",
        deleteGroup: "Delete Community",
        deleteGroupMsg: "Are you sure that you want to delete this community?",
        export: "Export",
        groupDeleteSuccess: "Community deleted successfully", 
        msg1:"You are about to delete",
        msg2:"This action CANNOT be undone. The group and its posts, members and files will be deleted forever.",
        update: "Update",
        sharePostPlaceholder: "Please select a group before sharing your post",
        removeAsAdmin: "Remove as admin",
        allUsers: "All users"
      },
      announcement: {
        createdBy:"Created By",
        filterByStatus:"Filter by status:",
        announcements: "Announcements",
        announcementDeleteSuccess:"Announcement deleted successfully.",
        announcementCancelSuccess:"Announcement cancelled successfully.",
        announcementTitle: "Announcements Title",
        noAnnouncement:"Looks like there's no announcement available yet",
        seeMore:"See more",
        seeLess:"See less",
        searchAnnouncement:"Search for announcements",
        effectiveDate: "Effective Date",
        expiryDate: "Expiry Date",
        status: "Status",
        action: "Action",
        createAnnouncement: "Create Announcement",
        details: "Details",
        recipients: "Recipients",
        publish: "Publish",
        review: "Review",
        announcementCancel:"Cancel",
        deleteAnnouncement:"Delete",
        createAnAnnouncement: "Create an announcement",
        updateAnnouncement: "Update announcement",
        announcementDescription: "Description",
        announcementTitlePlaceholder: "Please provide the subject of your announcement",
        announcementDescriptionPlaceholder: "Please provide the summary of your announcement",
        uploadPhoto: "Upload Photo",
        uploadPhotoDesc: "Select a photo of your announcement",
        reuploadPhotoDesc: "Choose another photo for your announcement",
        selectRecipients: "Select the recipients",
        selectBelowOptions: "Please select one of the below options",
        saveAsDraft: "Save as draft",
        publishNow: "Publish Now",
        publishLater: "Publish Later",
        announcementReview: "Announcement Review",
        preview: "Preview",
        showMore: "Show more",
        showLess: "Show less",
        effectiveDateGreaterThanExpiryDate: "Effective date should not be greater than Expiry date",
        effectiveTimeLessThanCurrentDate: "Effective date and time should be a future date and time",
        noRecordsFound: "No Records Found",
        loading: "Loading ...",
        searchIndividual: "Search Individual",
        cropImage: "Crop Image",
        effectiveDateMustbeAfterCurrentTime: "Effective Date must be after the current time",
        effectiveDateCannotUpdate: "The effective date cannot be updated as the announcement has been published",
        imageWarningMessage: "This file format is not supported. Please upload only jpeg, jpg, png or svg images"
      },
      gigs: {
        gigs: "Gigs",
        availableGigs: "Available",
        acceptedGigs: "Accepted",
        ongoingGigs: "Ongoing",
        closedGigs: "Closed",
        createGig: "Create",
        newGig: "New Gig",
        completedGigs: "Completed",
        updateGig: "Update",
        title: "Gig Title",
        description: "Description",
        skills: "Skills",
        gigType: "Gig Type",
        location: "Location",
        startDate: "Start Date",
        startTime: "Start Time",
        endDate: "End Date",
        endTime: "End Time",
        date: "Date",
        gigInformation: 'Gig Information',
        supervisor: 'Supervisor',
        assignedEngineer: 'Assigned Engineer',
        email: 'Email',
        timeline: 'Timeline',
        feedback: 'Feedback',
        emptyGig: "Looks like there's no gigs available yet",
        searchForGigs: "Search for Gigs...",
        options: "Options",
        gigDeleteMsg: "Gig Deleted Successfully",
        deleteGig: "Delete Gig",
        gigDeleteDesc: "Are you sure that you want to delete this Gig?",
        unitCategory: "Unit Category",
        selectRecipients: "Select recipients",
        everyone: "Everyone",
        specificGroup: "Specific Group",
        alreadySelected: "already selected",
        unit: "Unit",
        remove: "Remove",
        addUnit: "Add Unit",
        back: "Back",
        gigDetails: "Gig Details",
      },
      locations: {
        locationList: "Location List",
        viewMap: "View Map",
        createLocation: "Create Location",
        updateLocation: "Update Location",
        editLocation: "Edit Location",
        deleteLocation: "Delete Location",
        locationDetails: 'Location Details',
        information: 'Information',
        contact: 'Contact',
        supervisor: 'Supervisor',
        engineersStationed: 'Engineers Stationed',
        pastGigCompletion: 'Past Gig Completion',
        location: 'Location',
        locationName: 'Location Name',
        locations: 'Locations',
        searchForLocations: "Search for Locations...",
        people: 'People',
        options: "Options",
      },
      people: {
        people: "People",
        availableEngineers: "Available Engineers",
        leaves: "Absence",
        emptyAvailableEngineers: "Looks like there's no available engineers",
        absenceType: 'Absence Type',
        searchForLeaves: "Search for Leaves...",
        emptyLeaves: "Looks like there's no Leaves",
      },
      home: {
        home: "Home",
        yourActivities: "Progress this week",
        thisWeek: 'This week: ',
        lastWeek: 'Last week: ',
        userTrend: 'Since last week',
        companyTrend: 'Company trend',
        completed: 'Completed',
        earned: 'Earned',
        newQuest: "New Quest",
        whatsNext: "What's Next",
        yourProfile: "Your Profile",
        bannerHeader1: "Last week you're on a streak, ",
        bannerDesc:"Last week, you have completed <b>{goalsCount}</b> of your goals and <b>{questsCount}</b> quests. You have also earned over <b>{pointsCount}EP</b>. Let's do better this week.",
        bannerDescQuestAclOff:"Last week, you have completed <b>{goalsCount}</b> of your goals. You have also earned over <b>{pointsCount}EP</b>. Let's do better this week.",
        bannerDescLeft1: "Last week, you have completed",
        bannerDescMid1: "of your goals and",
        bannerDescRight1: "quests. You have also earned over",
        bannerDescRightEnd1: "Let's do better this week",
        bannerHeader2: "Welcome ",
        bannerDesc2:
          "Ready to achieve, grow, and be recognized? It starts here.",
        bannerDesc2QuestAclOff:
          "Hope you are refreshed for a new week of productivity. Lets start by setting your goals to earn points.",
        employee: "Personal View",
        manager: "Team Insights",
        homePageError: "Oops!! Something went wrong. Please try again.",
        attachmentWarning: "You can only upload up to 1 file for each post.",
        engagementAnalysis: "Engagement Analysis"
      },
      quest: {
        quests: 'Quests',
        createdBy:"Created By",
        createdDate:"Created Date",
        updatedDate:"Updated Date",
        quest: "Quest",
        placeholder:"Search quest",
        groupPlaceholder:"Search quest group",
        subPlaceholder:"Search quest sub group",
        groupquest: "Quest Group",
        incorrectEmail:"Error! Email(s) format is invalid",
        incorrectSeperator:"Please use unique email separator (comma/semicolon/new line)",
        verifySeperator:"Verify email(s)",
        emailNotExist:"Error! Email(s) does not exist in the system",
        ongoing: "Ongoing",
        completed: "Completed",
        moderator: "Moderator",
        moderators: "Moderators",
        points: "Points",
        done: "Done",
        status: "Status",
        submission: "Submission",
        reject: "Reject",
        approve: "Approve ",
        badge: "Badge",
        timeLeft: "Time Left",
        dueby: "Due by",
        created: "Created",
        started: "Started",
        emptyQuest: "What? Did we run out of quests?",
        secEmptyQuest: " Don't worry. We'll notify you when there is a new quest for you.",
        moderatorEmptyQuest: "Well done!",
        moderatorSecEmptyQuest: "No quests are waiting for your review.",
        completedEmptyQuest: "You have not completed any quests yet.",
        completedSecEmptyQuest: "Check back later once you've completed the quests.",
        bannerHeader: "Be the master of your destiny",
        bannerDescLeft: "Conquer quests and compete with your team! You have <b>",
        bannerDescMid: "</b> ongoing ",
        admin: 'Admin',
        details: 'Details',
        action: 'Action',
        reward: 'Reward',
        recipient: 'Recipient',
        review: 'Review',
        completeQuestAction: 'Complete Quest Action',
        canNotInactivateGroup:"There is active quest associated to it",
        cantInactivate:"Can't Inactivate",
        completeSpecificSurvey: 'Complete a specific survey',
        setCustomRules: 'Set custom rule',
        modarator: 'Moderator',
        moderatorPlaceholder: 'Type or search from the droplist',
        taskDescription: 'Task Description',
        taskDescriptionPlaceHolder: 'Type the task description',
        hint: 'Hint',
        rewardType: 'Reward Type',
        value: 'Value',
        questTitle: 'Quest Name',
        questtitle:"Quest name",
        groupquesttitle:"Quest group",
        subgroupquesttitle:"Quest sub group",
        questDescription: 'Description',
        skills: 'Skills',
        activePeriod: 'Active Period',
        startDate: 'Start Date',
        endDate: 'End Date',
        expirationPolicy: 'This quest does not have an expiration date.',
        questTitlePlaceholder: 'Give a name to your quest',
        groupQuestTitlePlaceholder: 'Give a name to your quest group',
        subGroupQuestTitlePlaceholder: 'Give a name to your quest sub group',
        descriptionPlaceholder: 'Give a description to your quest',
        groupDescriptionPlaceholder: 'Give a description to your quest group',
        subGroupDescriptionPlaceholder: 'Give a description to your quest sub group',
        categoryPlaceholder: 'Choose your quest type',
        groupCategoryPlaceholder: 'Choose your quest group',
        subGroupCategoryPlaceholder: 'Choose your quest sub group',
        selectStatus:'Change Your Sub Quest Status',
        recipientHeader: 'Set the recipients',
        questWarning: "*This action rule requires a moderator to approve the task completion.",
        mandatoryFileUpload: "Mandatory File Upload",
        excludeModeratorFromQuestRecipients: "Exclude moderator   from quest recipients",
        addQuestAction: "Add quest Action",
        questName: "Quest Name",
        unitCategory: "Unit Category",
        unit: "Unit",
        category: "Quest Type",
        groupcategory:"Quest Group",
        subGroupCategory:"Quest Sub Group",
        createdTime: "Created Time",
        updatedTime: "Updated Time",
        status: "Status",
        deleteQuest: "Delete Quest",
        deleteQuestMsg: "Are you sure that you want to delete this Quest?",
        searchForQuest: "Search for Quest...",
        customRule: "Custom rule",
        onboarding: "Onboarding",
        addProfilePicture: "Add profile picture",
        loginToApp: "Login to the app",
        occurOnce: "Occur Once",
        occurDaily: "Occur Daily",
        occurWeekly: "Occur Weekly",
        occurMonthly: "Occur Monthly",
        createNewQuest: "Create New Quest",
        createGroupQuest:"Create Quest Group",
        createSubGroupQuest:"Create Quest Sub Group",
        questGroupCategory:'Quest Group',
        subQuestGroupCategory:'Quest Sub Group',
        subQuestGroup:'Quest Sub Group',
        questHasBeenApproved: " quest has been Approved!",
        questHasBeenRejected: " quest has been rejected!",
        approveQuest: "Approve Quest",
        questTaskToBeCompleted: " quest task to be completed.",
        rejectQuest: "Reject Submission",
        questResubmitForApproval: " will have to resubmit the quest task for approval.",
        attachment: "Attachment",
        notes: "Notes",
        attachmentUploadedSuccessfully: "Attachment Uploaded Successfully",
        internalErr: "Something went wrong!",
        fileTypeNotAccepted: "Sorry! This file type is not accepted due to security reasons.",
        fileLimitValidation: "You can only upload a maximum of one file!",
        dragFilesToUpload: "Drag files here to upload",
        years: " years",
        months: " months",
        days: " days",
        hours: " hours",
        minutes: " minutes",
        seconds: " seconds",
        file: "File",
        questAttachmentPlaceholder: "Insert your response to the quest task. You can paste your links here.",
        questNotFound: "The quest you're looking for is not found or no longer active",
        selectRecipients: "Recipients",
        everyone: "Everyone",
        specificGroup: "Specific Group",
        individual: "Individual",
        groupOfUser:"Group of users",
        message:"Enter the list of recipients email id(s) separated by comma, semi-colon or a new line.", 
        remove: "Remove",
        addAnotherUnit: "+ Add another unit",
        to: "To",
        proveYourAndroidSkills: "Prove your beginer Android Dev skills by completing a basic app",
        start: "Start",
        questPreview: "Quest Preview",
        badges: "Badges",
        filter: "Filter",
        searchBy: "Search by:",
        searchForBadges: "Search for badges",
        setupRewardForQuest: "Setup the reward for the Quest",
        questTaskHasBeenCompleted: "Your quest task has been completed!",
        questHasBeenSubmitted: "Your quest has been submitted for approval!",
        submitForReview: "Submit for review",
        reviewQuestCompletion: " will have to review your quest completion.",
        bannerDesc: "Be a better version of yourself. Pick the next quest to challenge yourself!",
        teamsTooltip: "User has to tag bot and type in bot command to complete the quest <br>e.g. <b>@selfdrvn Share</b> This is my first post</br>",
        questRejectionTitle: "Kindly give reason for rejection",
        questRejectionPlaceholder: "Give reason and Instructions for resubmission",
        addAction: '+ Add action',
        emptyAdminQuest: "It looks like there are no quest yet. Start by adding one right now.",
        addSkills: 'Add Skills',
        questExpired: 'Expired',
        questDeleteSuccess: 'Quest deleted successfully.',
        questUpdateSuccess: 'Quest updated successfully.',
        questCreateSuccess: 'Quest created successfully.',
        questUpdateSuccess: 'Quest updated successfully.',
        selectAction: 'Select action',
        selectUnitCategory: 'Select Unit Category',
        selectUnit: 'Select Unit',
        selectValue: 'Select a value',
        hashTagHeader: 'Insert Hashtag',
        postTeamsUrl: 'POST IN THE TEAMS CHANNEL',
        postTeamsUrlLabel: 'Url',
        postTeamsUrlPlaceholder: 'Specify teams channel url',
        postTeamsHashTagUrl: 'POST HASHTAG IN TEAMS CHANNEL',
        apply: 'Apply',
        hashtagMessage: 'What hashtag should the user out in their post?',
        hashTagPlaceHolder: 'Insert the tag here',
        visitLinkHeader: 'Visit a link',
        visitLinkTitle: 'Title',
        specifyUrl: 'Specify Url',
        Url: 'Url',
        selectQuiz: 'Select quiz',
        scoreTitle: 'Score Requirement',
        scoreDesc: 'How much should a person score to pass this quest task?', 
        noRequirement: 'No Requirement',
        withRequirement: 'With Requirement',  
        score: 'Score',   
        selected: 'Selected',
        confirmation: 'Confirmation',
        ActivateQuest: 'Are you sure you want to set this quest to Active?',
        InactivateQuest: 'Are you sure you want to set this quest to Inactive?',
        DuplicateQuestMessage: "The quest action cannot be duplicated",
        DuplicateUnitCategory: "Unit category cannot be duplicated",
        selectPoll: 'Select Poll',
        commonAll: 'All',
        unitCategoryLabel: 'Unit Category',
        unitLabel: 'Unit',
        CategoryLabel: 'Quest Type',
        GroupCategoryLabel: 'Group Quest Type',
        SubGroupCategoryLabel: 'Sub Group Quest Type',
        StatusLabel: "Status",
        selectSurvey: "Select Survey",
        pointsRequired: "Points are Required",
        pointsMinErr: "Point must be greater than 0",
        pointsMaxErr: "Point must be less than 999999999",
        AddProfilePicture: "Add a profile picture",
        UpdateProfilePicture: "Update your profile picture {{value}} times",
        completeProfileInfo: "Complete your profile information",
        postNewsFeed: "Post in the newsfeed",
        postNewsFeedTimes: "Post {{value}} times in the newsfeed",
        sharePost: "Share a post to social media",
        sharePostTimes: "Share {{value}} posts to social media",
        likingPost: "Like a post",
        likingPostTimes: "Like {{value}} posts",
        commentPost: "Comment on a post",
        commentonPostTimes: "Comment on {{value}} posts",
        AnswerPoll: "Answer a poll",
        AnswerPollTimes: "Answer {{value}} polls",
        createPoll: "Create a poll",
        createPollTimes: "Create {{value}} polls",
        completePoll: "Complete poll",
        postHashtag: "Post hashtag in newsfeed",
        createGoal: "Create a goal",
        createGoalTimes: "Create {{value}} goals",
        completeGoal: "Complete a goal on time",
        completeGoalTimes: "Complete {{value}} goals on time",      
        completeSurvey: "Complete a survey",
        completeSurveyTimes: "Complete {{value}} survey",
        completeSpecificQuiz: "Complete quiz : ",
        completeQuizScore: "Score {{value}}% on : ",
        completeQuiz: "Complete a quiz",
        completeQuizTimes: "Complete {{value}} quizzes",
        RequestFeedback: "Request {{value}} feedback",
        RequestFeedbackTimes: "Request {{value}} feedbacks",   
        GiveFeedback: "Give {{value}} feedback",
        GiveFeedbackTimes: "Give {{value}} feedbacks",
        EarnBadge: "Earn a badge",
        EarnBadgeTimes: "Earn {{value}} badges",
        AnswerMessageInBottle: "Answer a message in a bottle",
        AnswerMessageInBottleTimes: "Answer {{value}} message in a bottle",
        createPostWithMediaContent: "Create a post with media content and #{{value}} hashtag",
        tooltipEdit: "Edit",
        QuestDelete: "Delete",
        changeGroupQuest:'Change quest group/sub group',
        changeGroupSubGroupQuest:"Change Quest Group/Sub Group",
        QuestDuplicate: "Duplicate",
        ChangeDueDate: "Change Due Date",
        updateEndDate: "Update end date",
        endDateMsg: "This action will update the end date. Are you sure?",
        endDateConfirm: "Yes, Change the date",
        ManageColumns: "Manage Columns",
        quizMissingError: "Input required for the quest action is missing.",
        showFilter: "Show filter",
        hideFilter: "Hide filter",
        groupQuestCategory:"Quest Group",
        subgroupQuestCategory: "Quest Sub Group",
        questPeriod: "Quest Period",
        reset: "Reset",
        applyFilter: "Apply Filter",
        select: '--Select--',
        questFilterResetConfirmationMsg: 'Are you sure you want to reset this filter?',
        confirmReset: 'Yes, Reset',
        searchQuest: 'Search quest',
        anonymousFeedbackMsg:"Send an anonymous feedback",
        questWidgetMsg:"Click on the quests to approve or reject them"
      },
      leaderboard: {
        leaderboard: "Leaderboard",
        teamLeaderboard:"Team Leaderboard",
        overall: "Overall",
        team: "Team",
        no:"No.",
        lead:"Leading",
        pointsAndBadges:"Points & Badges",
        steps:"Steps",
        avgPoints:"Avg Points",
        bannerHeader: "Everyone is a winner! See who's on the leaderboard.",
        bannerDesc:"Be on the leaderboard. You deserve it!",
        weekly: "Weekly",
        monthly: "Monthly",
        allTime: "All Time",
        myStanding: "My Standing",
        emptyPoints: "Winners wanted! Make the first move now.",
        previousWeek: "Previous Week",
        badges: "Badge(s)",
        stepathon: "Stepathon",
        individual: "Individual",
        teamStepathon: "Team",
        emptyStepathonSteps: "Winners wanted! Make the first move now.",
        tabInfo:"Here's a quick guide to setting up the selfdrvn tab in Microsoft Teams",
        needMore: "Need more Help?",
        myRank:"My rank",
        aboveMe:"Above me",
        belowMe:"Below me",
        totalPoints:"Total earned points",
        myPoints:"My points",
        badgesEarned:"Badges earned",
        viewAll:"View all",
        availablePoints:"Available points"
  
      },
      teamsleaderboard: {
        note: "Please note:",
        activeSelfDrvn: "1. You need to have an active SelfDrvn company account to use this app.",
        allUsers: "2. All users need to be active and part of the same SelfDrvn company account.",
        requestforademo: "3. Don't have an account? Request for a demo at contact@selfdrvn.com and one of our Customer Success Managers will be in touch with you soon!"
      },
      myPoints: {
        rewardedBy: "Rewarded By",
        badge: "Badge",
        redemptionItem: "Redemption Item",
        points: "Points",
        myPoints: "My Points",
        currentPoints: "Current Points",
        spent: "Spent",
        pending: "Pending",
        totalPoints: "Total Points",
        balance: "Balance",
        pointBalance: "Point Balance : ",
        type: "Type",
        awardedBy: "Awarded By",
        emptyPoints: "Earn reward points by doing your best!"
      },
      redemption: {
        emptyHistoryRewards: "It looks like there are no items in your history yet.",
        redemptionInfo: "Redemption Info",
        description: "Description",
        redemption: "Redemption",
        featured: "Featured",
        history: "History",
        wishlist: "Wishlist",
        bannerHeader: "Celebrate your achievements. Reward yourself",
        bannerDesc: "Exceptional items curated specially for you. Spend your hard-earned points wisely. ",
        categories: "Categories",
        seeAll: "See All",
        emptyRewards: "Good things come to those who wait. Check back here soon!",
        justForYou: "Just For You",
        topRewards: "Top Rewards",
        redemptionInfo: "Redemption Info",
        status: "Status",
        expiringOn: "Expiring on:",
        activateBefore: "Activate before:",
        Redeem: "Show voucher",
        emptyWishlistRewards: "It looks like there are no items on your wishlist yet.",
        status: "Status:",
        rewardAddedToWishList: "Reward has been added to your Wishlist",
        insufficientPoints: 'Insufficient Points',
        redeem: "Redeem",
        addToWishList: "Add to Wishlist",
        left: '  Left',
        quantity: "Quantity",
        cost: "Cost",
        perPerson: "Per Person",
        instantApproval: 'Instant Approval',
        approvalRequired: 'Approval Required',
        redeemRewardSuccess: 'Redeem Reward Success',
        back: "Back",
        redeemNow: 'Redeem Now',
        rewardRemovedFromWishList: "Reward has been removed from your Wishlist ",
        searchAllRedemptionItems: "Search all redemption items",
        historyNotAvailable: "You don't have permission to view this redemption item",
        outOfStock: "Out of stock"
      },
      approveGoal: {
        alertTitle: "Approve Goal",
        alertbody: "Acknowledge the completion of ",
        goal: "goal",
        approve: "Approve",
      },
      completeGoal: {
        alertTitle: "Complete Goal",
        alertbody: "Are you sure that you want to complete this goal?",
        submit: "Submit",
      },
      deleteGoal: {
        alertTitle: "Delete Goal",
        alertbody: "Are you sure that you want to delete this goal?",
        delete: "Delete",
      },
      rejectGoal: {
        alertTitle: "Reject Goal",
        alertbodyleft: "Something wrong with ",
        alertbodyright: " goal? What's the reason?",
        reject: "Reject",
      },
      submitGoal: {
        alertTitle: "Submit Goal",
        alertbody:
          "By submitting this goal, all task will be completed and submitted for review by ",
        submit: "Submit",
      },
      lazyLoading: {
        suspense: "I am working on it ...",
      },
      logoutDialog: {
        modalTitle: "We will miss you",
        modalBody: "Are you sure you want proceed?",
        modalFooter: "Go back",
        continue: "Continue",
      },
      sideNavBar: {
        logoText: "SelfDrvn",
        admin: "Admin",
        goalSetting: "Goal Setting",
        reward: "Reward",
        locations: "Locations",
        gigs: "Gigs",
        people: "People",
        quest: "Quests",
        polls: "Polls",
        goalSetting: "Goals",
        recognize: "Recognize",
        quiz: "Quiz",
        reward: "Rewards",
        organization: "Organization",
        info: "Info",
        rmDashboard: "Dashboard",
        GigArenaHeader: "GigArena",
        survey: "Survey",
        dashboard: "Dashboard"
      },
      notFound: {
        topText: "This page does not exist.",
        bottomText:
          "We looked everywhere for this page.Are you sure the website URL is correct? Get in touch with our support team for help.",
        mailId: "support@selfdrvn.com",
      },
      featureNotFound: {
        topText: "Feature not available",
        bottomText:
        "You don't have access to this page.",
        bottomText1:
        "Please contact the administrator for more information.",
        goBackToHome: "Go Back To Home"
      },
      sessionExpired: {
        topText: "Your Session has expired.",
        bottomText: "Please click on refresh to get back.",
        refresh: "Refresh"
      },  
      sessionExpired: {
        topText: "Your Session has expired.",
        bottomText: "Please click on refresh to get back.",
        refresh: "Refresh"
      },  
      goalSetting: {
        goals: 'Goals',
        goalSetting: "Goal Setting",
        yourGoals: "Your Goals",
        editGoal: "Edit Goal",
        newGoal: "New Goal",
        targeting: "What is the Key Result You are Targeting?",
        goalAlignment: "Goal Alignment",
        addTask: "Add Task",
        reviewee: "Reviewee",
        maxDateMessage: "Date for Remind Me should not be later than due date",
        task: "Task",
        taskName: "Task Name",
        deleteTheTask: "Delete the Task",
        dueDate: "Due Date",
        remindMe: "Remind Me (Optional)",
        strin: "strin",
        updateGoal: "Update Goal",
        startGoal: "Start Goal",
        emptyGoals: "It looks like there are no goals yet. Start by adding one right now.",
        teamEmptyGoalsPrimary: "It looks like there are no goals added yet.",
        teamEmptyGoalsSecondary: "Motivate your team with clear and meaningful goals. Start by adding one now.",
        deleteGoal: "Delete Goal",
        reviewer: "Reviewer",
        reject: "Reject",
        approve: "Approve",
        sGoal: "'s Goal",
        selectGoalAlignments: "Select Goal Alignments",
        teamGoals: "Team Goal",
        bannerHeader: "Dream big! What goals are you going after?",
        bannerDesc: "Create and monitor your goals with ease. Measure what matters for growth.",
        hasNotStarted: "Has not started",
        ongoing: "Ongoing",
        pendingReview: "Pending Review",
        completed: "Completed",
        submitForReview: "Submit for review",
        completeGoal: "Complete Goal",
        noGoals: "No Goals",
        goalStatus: "Goal Status",
        addNewGoal: "Add New Goal",
        teamMembers: "Team Members",
        selectReviewee: "Select Reviewee",
        selectReviewer: "Select Reviewer",
        goalNotFound: "The goal you are looking for is already deleted.",
        goalOwner: "Goal owner",
        titleValidation: 'Title cannot be blank',
        goalValidation: 'Goal Alignment must be selected',
        reviewValidation: 'Reviewer must be selected',
        revieweeValidation: 'Reviewee must be selected',
        dueDateValidation: 'Due Date cannot be blank',
        goalTitleLabel: 'What is the Key Result You are Targeting?',
        goalSuccess: "Goal Created Successfully",
        goalUpdate: "Goal Updated Successfully",
        dateValidation: 'Remind me date should not be later than due date',
        loading: 'Loading...',
        noResults: 'No Results',
      },
      rmDashboard : {
        overViewTab: "Overview",
        LeaveTab: "Leaves",
        ExportDataButton: "Export Data",
        CurrentDayAction: "Current day actions",
        EngineersOnLeave: "Engineers on leave",
        EngineersWhoAreLate: "Engineers who are late",
        ListOfGigsOpenToday: "List of gigs open today",
        ListOfAvailableReplacementEngineers: "List of available replacement engineers",
        ListOfEngineersAppliedLeaveForNext5Days: "List of engineers applied leave for next 5 days", 
        emptyEngineersLate: "Looks like there's no Late Engineers",
        leaveDate : "Leave Date",
        supervisor: 'Supervisor',
        supervisorName: 'Supervisor Name',
        gigStartIn: 'Gig Start in',
        rmActionRequired: 'RM Action Required',
        csmActionRequired: 'CSM Action Required',
        replacementEngineerFound: 'Replacement Engineer Found',
        replacementFoundAutomatically: 'Replacement Found Automatically',
        replacementEngineer: 'Replacement Engineer',
        replacementEngineerRating: 'Replacement Engineer Rating',
        emptyEngineers: "Looks like there's no Enngineers",
        engineersLeaveForNextFiveDays: 'List of Engineers applied leave for next 5 days',
        emptyReplacementEngineers: "Looks like there's no Replacement Engineers",
        listOfOpenGigsToday: "List Of Gigs Open Today",
        emptyOpenGigs: "Looks like there's no Open Gigs",
        nearbyLocation: "Nearby Location",
        rating: "Rating",
        status: "Status",
        leavesApplied: "Leaves applied",
        resourceAppliedLeave: "resource applied leave",
        lateResources: "Late resources",
        lateResource: "late resources",
        gigsToBeFilled: "Gigs to be filled",
        gigsToFill: "gigs to be filled",
        replacementAvailable: "Replacement available",
        replacementsAreAvailable: "replacements are available",
      },
      quiz: {
        bannerHeader: "Prove your knowledge by acing these brain teasers.",
        all: "All",
        ongoing: "Ongoing",
        expired: "Expired",
        completed: "Completed",
        published:"Published",
        drafts: "Drafts",
        admin: "Admin",
        user:"User",
        quiz:"Quiz",
        quizes:"Quizes",
        addNewQuiz:"Add New Quiz",
        republishQuiz:"Republish Quiz",
        republish: "Republish",
        exportData:"Export Data",
        admin: "Admin",
        timeLeft: "Time Left",
        edit:"Edit",
        unpublishQuiz:"Unpublish Quiz",
        addParticipants:"Add Participants",
        export:"Export",
        shareLink:"Share Link",
        publishedResponses: "How well you know your company?",
        users:"Users",
        sentOn:"Sent on",
        responded:"Responded",
        pending:"Pending",
        score:"Score",
        hasNotResponded:"Has not responded",
        title: "Quiz Title",
        titlePlaceholder:"Enter quiz title here",
        description:"Quiz Description",
        descriptionPlaceHolder:"Enter quiz description here",
        quit:"Quit",
        publish:"Publish",
        saveAsDraft:"Save As Draft",
        details:"Details",
        settings:"Question Settings",
        switch:"Randomize options order",
        randomize:"Randomize the order of the answers shown in each question",
        question:"Question ",
        scoreInfo:"Please assign score according to the difficulty of the question",
        multipleChoice:"Multiple Choice",
        singleChoice:"Single Choice",
        maxSixChoices: "Maximum 6 Choices",
        pollCloseOn: "Poll closes on",
        nextQuestion:"+ Next Question",
        remove:"Remove",
        rightAnswerInfo:"Add Right Answer Text",
        wrongAnswerInfo:"Add Wrong Answer Text",
        addOption: "+ Add Option",
        questionGraphic: "Question Graphic",
        addQuestionGraphic:"Add Question Graphic",
        description: "Description",
        quizMe: "Quiz Me!",
        completedQuiz: "Completed - See Result",
        ongoigQuizAnswered: "people have already completed this quiz",
        completedQuizAnswered: "people have already answered this quiz",
        expiredQuizAnswered: "You did not respond to this quiz",
        isCorrectMsg:"Well done!",
        wrongAnswerMsg: "Oops, that's not quite correct. No worries, you'll get it on the next try.",
        submitQuiz:"Submit Quiz",
        selectMoreText:"select more than one answer",
        question: "Question",
        confirm: "Confirm",
        confirmText: "Are you sure?",
        confirmSubtext: "You cannot retake this quiz after you have viewed the answers",
        confirmSubheader: "Do you want to quit the page?",
        addNewQuizSubHeader: "Want to save your changes?",
        discardText: "Do you want to discard the quiz?",
        publishEditText: "Are you sure you want to continue?",
        publishEditSubtext: "The users' response will reset after publishing the edited quiz.",
        days: "Days",
        youCompleted: "You've completed",
        attemptsLeft: "Attempts Left",
        retakeQuiz: "Retake Quiz",
        viewAnswers: "View Answer",
        quizInvitation: "Quiz Invitation",
        respondents: "Respondents",
        subject: "Subject",
        message: "Message",
        publishDate: "Publish Date",
        expiryDate: "Expiry Date",
        optional: "Optional",
        expiredNotificationText: "Oops, you miss it.",
        expiredNotificationSubText: "This quiz has expired.",
        remindUsersBy: "Remind Users by",
        numberOfAttempts: "Number of Attempts",
        addNewQuest: "Add to a new quest",
        back: "Back",
        quizInvitationInfo:"Creates a new quest with this quiz as one of it's quest actions",
        dateText: "Date is according to GMT+8",
        daysSubmission: "Days Before Submission",
        selectQuizToRepublish:"Select quiz to republish",
        everyone: "Everyone",
        yes:"Yes",
        yesGoBack: "Yes, Go Back",
        remindLabel: "Days remaning until due date",
        unlimitedAttemptsLabel: "0 = unlimited attempts",
        dateRangeText: "Apply",
        quizBannerDesc:"Taking a quiz tests your understanding, helps you retain the info you already have, and identifies gaps in your knowledge so you can get more help where needed. What's more - they're fun! So go ahead and give it a go!",
        quizSubject: "New Quiz Created For You",
        quizMessage: "There's a new quiz created just for you! Come and try it",
        quizDateValidationMsg: "Reminder days cannot be exceeding the difference in days between expiry date and publish date",
        quizUpdationMsg: "You have successfully updated the quiz",
        quizPublishMsg: "You have published quiz successfully",
        internalErr: "Something went wrong",
        userValidationMsg: "You must select atleast one responder",
        quizContent: "<p>There's a new quiz created just for you! Come and try it!</p>",
        quizRepublishMsg: "You have republished quiz successfully",
        addParticipantsMsg: "Participants added successfully", 
        addParticipantMsg: "Participant added successfully",
        publishDateExceedMsg: "Publish date and time should not be later than expiry date and time",
        expirtyDateExceedMsg: "Expiry date and time should not be earlier than publish date and time",
        draftUpdationMsg: "Quiz draft updated successfully",
        draftSaveMsg: "Your quiz has been saved as a draft",
        no: 'No',
        quizMissedMsg: "Oops! You Missed It!",
        quizNotAvailable: "Not available.",
        quizExpMsg: "This quiz has expired.",
        quizCancelMsg: "This quiz has been cancelled.",
        quizNotAvailableMsg: "The quiz is not available" ,
        quizNotInvitedMsg: "You are not invited to this quiz",
        answerAllValidationMsg: "You have to answer all the questions",
        awesome: "Awesome",
        awesomeMsg: "That's an A+ in our books!",
        goodJob: "Good job!",
        goodJobMsg: "Good job! There's just a little more room for improvement, keep it up!",
        goodAttempt: "Good attempt!",
        goodAttemptMsg: "We're happy you learned a lot from the quiz, you'll ace it next time!",
        lessPercentageMsg: "You have so much potential to be better than you already are, never stop learning, alright!",
        videoSizeExceedMsg: "Uploaded video cannot exceed 50MB",
        fileNotSupportMsg: 'File format is not supported',
        selectAnsMsg: "Select at least one option as answer",
        selectOptMsg: "Option cannot be left blank",
        selectScoreMsg: "Score cannot be left blank",
        selectQuestionMsg: "Question cannot be left blank",
        selectDescMsg: "Description cannot be left blank",
        selectTitleMsg: "Title cannot be left blank",
        selectDuplicateMsg: "Duplicate options are not accepted",
        modifiedBy: "Modified By",
        datePublished: "Date Published",
        dueDate: "Due Date",
        participants: "Participants",
        responses: "Responses",
        status: "Status",
        action: "Action",
        createdBy: "Created By",
        dateCreated: "Date Created",
        dateModified: "Date Modified",
        deleteQuiz: "Do you want to delete this quiz?",
        publishDescForUnavailable: "The users response will be reset",
        quizzes: "Quizzes",
        searchForQuiz: "Search Quiz",
        emptyQuizPrimary: "It looks like there are no quizzes for you.",
        emptyQuizSecondary: "Don't worry. We'll notify you when there's a new one.",
        quizDeleteMsg: "Quiz Deleted Successfully",
        deleteQuizWarning: "Are you sure that you want to delete this Quiz?",
        adminQuizEmptyPrimary: "It looks like there are no quizzes created yet.", 
        adminQuizEmptySecondary: "Engage your learners by creating a quiz now.", 
        noAttemptsErr: "You have 0 attempts left to answer the quiz",
        alreadyViewed: "You already view the quiz answer. You cannot answer the quiz anymore.",
        alreadyCompleted: "You already completed the quiz. You cannot answer the quiz anymore.",
        noRepublishQuiz: "It looks like there are no quizzes to republish",
        loading: "Loading... ",
        shareLinkMessageOne: "Link to",
        shareLinkMessageTwo: "has been copied",
        copy: "Copy",
        copied: "Copied",
        SharlinkTitle: "Copy Link",
        quizNotAvailMsg: "The quiz is no longer available"
      },
      feedback:{
        feedback: 'Feedback',
        overview: 'Overview',
        received: 'Received',
        given: 'Given',
        request: 'Requested',
        manager: 'Manager',
        hrOverview: 'HR Overview',
        bannerHeader: 'Help your colleagues improve. Start by providing feedback to them.', 
        feedbackReceived: 'Feedback Received',
        positive: 'Positive',
        constructive: 'Constructive',
        giveFeedback: 'Give Feedback',
        reqFeedback: 'Request Feedback',
        seeFeedback: 'View Feedback',
        giveFeedbackText: 'Provide Feedback to your team either positive or constructive',
        reqFeedbackText: 'Request Feedback to your team either positive or constructive',
        createGoal: 'Create Goal',
        recentltReceived: 'Recently Received',
        teamCompetency: 'Team Competency',
        seeAll: 'See All',
        teammaates: 'Teammates',
        exportFeedbackData: 'Export Feedback Data',
        projectOrTaskTitle: 'Project or Task Title',
        selectTeamMember: 'Select Team Member',
        giveNext: 'GiveNext',
        competency:"Select Competencies",
        date: 'Event Date',
        recognise: 'Recognise',
        ratePerson: 'How would you rate your team member in this area?',
        message: 'Message',
        thisWeek: 'This Week',
        thisMonth: 'This Month',
        last3Months: 'Last 3 Months',
        last6Months: 'Last 6 Months',
        last12Months: 'Last 12 Months',
        doingGoodAt: 'Doing good at',
        improveOn: 'Need to improve on',
        peersRequest: 'Peers Request',
        yourRequest: 'Your Request',
        highPerformers: 'High Performers',
        needIntervention: 'Needs Intervention',
        viewMore: 'View More',
        export: 'Export',
        competencyHeatMap: 'Competency Heatmap',
        allMyCompetencies: 'All My Competencies',
        feedbackSummary: 'Feedback Summary',
        emptyOverviewPrimary: "Oops! You haven't got any feedback.",
        emptyOverviewSecondary: 'Start by requesting feedback from your peers and manager.',
        emptyReceivedPrimary: "Oops! You haven't got any feedback.",
        emptyReceivedSecondary: 'Start by requesting feedback from your peers and manager.',
        emptyGivenPrimary: 'You have not given any feedback yet.',
        emptyGivenSecondary: 'Would you like to start by giving feedback to your peers and manager?',
        emptyPeersPrimary: 'You have not received any feedback requests.',
        emptyYoursPrimary: 'You have not requested any feedback yet.',
        emptyYoursSecondary: 'Start by requesting feedback from your peers and manager.',
        emptyManagerPrimary: "Your team has not got any feedback for improvement.",
        emptyManagerSecondary: 'Please help them by giving them some feedback now.',
        selectCompetencyPH: "Select competency",
        eventPH: "Enter the title or name of the project",
        messagePH: "Type your message here...",
        awesome: "Awesome!",
        pastSixMonths: "Past 6 Months",
        pastYear: "Past Year",
        constructiveFeedbackMsg: "you have received 17 of constructive feedback on communication",
        feedbackGoal: "Would you like to create a goal to help you improve on it?",
        dismiss: "Dismiss",
        feedbackBannerDescPrimary: "Constructive feedback helps your peers to improve and motivate. This week you have given ",
        feedbackBannerDescSecondary: " feedback",
        feedbackBannerDescSecondary1: " feedbacks",
        feedbackBannerDescSecondary: " feedback",
        feedbackBannerDescSecondary1: " feedbacks",
        reqFeedbackMsg: "requested your feedback",
        sentFeedbackMsg: "sent you a feedback",
        receivedFeedbackMsg: "received your feedback",
        receivedReqMsg: "received your request",
        eventError: "Title length should be less than 100 characters.",
        giveModalDatePH: "Select the date",
        reqModalPH: "Enter the date of project",
        anonymous: "Anonymous",
        ratingWarning: "Please select a valid rating for the competency (1-5)",
        loading: "Loading ...",
        anonymousFeedback: "Send an anonymous feedback",
        employeeName: "Employee Name",
        level: "Level",
        avgRating: "Avg Rating",
        belowPar: "Below Par",
        onPar: "On Par",
        exceedingExpectation: "Exceeding Expectation",
        projectManagement: "Project Management",
        level1: "Level1",
        readyForPromotion: "Ready for Promotion",
        accountManager: "Account Manager",
        planning: "Planning",
        viewAllCompetencies: "View all competencies",
        createGoalToday: "Create goal today",
        feedbackModalTitleLength: "Title length should be less than 100 characters",
        selectTeamMembers: "Select Team Members",
        feedbackCancelText: "You will lose your data. Are you sure you want to cancel?",
        feedbackOn: "Feedback on",
        competencies: "Competencies",
        feedBackTo: "Feedback To",
        warning: "Want to save your changes?",
        confirmationPopupHeader: "Your action is not completed",  
        teamInsights: "Manager",
        noCompFound: "No competencies available"
      },
      organizationInfo: {
        uploadImage: 'Please upload an image',
        selectImage: 'Please select an Image',
        organizationInfo: "Organization Info",
        organizationName: "Organization Name",
        organizationLogo: "Organization Logo",
        country: "Country",
        state: "State",
        pincode: "Pin code",
        city: "City",
        telephoneNumber: "Telephone Number",
        faxNumber: "Fax Number",
        uploadImg: "Upload an Image",
        dragToUpload: "Drag files here to upload",
      },
      recognise: {
        individual: "Individual",
        team: "Team",
        recognize: "Recognize",
        recogniseBudget: "Recognize Budget",
        spent: "Spent",
        giveReward: "Give Reward",
        overview: "Overview",
        allocatedBudget: "Allocated Budget",
        totalSpent: "Total Spent",
        currentBalance: "Current Balance",
        newestToOldest: "Newest to Oldest",
        oldestToNewest: "Oldest to Newest",
        highestPointsToLowest: "Highest Points to Lowest",
        lowestPointsToHighest: "Lowest Points to Highest",
        pointsPerRecipient: "Points per recipient",
        emptyRecognise: "You haven't recognized anyone yet. Start recognising now.",
        searchByNameAndRewardName: "Search by name and reward name",
        category: "Category",
        message: "Message",
        emptyRewards: "No reward template is available.",
        emptyRewards1: "Contact your admin to create reward template for you",
        confirmRecognise: "Confirm to recognize?",
        warning: "You will not be able to undo recognition once sent.",
        defaultMsg: "Thanks for putting in the effort! It means a lot to us!",
        pointsExceedErrMsg: "Total points rewarded to all recipients will exceed your current balance",
        minValue: "Minimum value is ",
        selectReward: "1.Select Reward",
        selectRecipient: "2.Select Recipient",
        editAndSend: "3.Edit and Send",
        send: "Send",
        all: "All",
        points: "Points",
        badges: "Badges",
        pointsAndBadges: "Points and Badges",
        nameAlphabetically: "Name Alphabetically",
        highestBalanceToLowest: "Highest Balance to Lowest",
        lowestBalanceToHighest: "Lowest Balance to Highest",
        searchByIndividual: "Search by Individual",
        searchByTeam: "Search by Team",
        recipients: "Recipient(s)",
        selectAll: "Select All",
        searchByRewardName: "Search by reward name",
        pointsRoundOffMsg: "The points value is always round off to the nearest multiple of {{defaultPoints}}",
        preview: "3.Preview",
        confirmAndSend: "4.Confirm and Send",
        confirmToRecognize: "Confirm to recognize?",
        recognigeConfirmTeams: "You will not be able to undo this action once sent.",
        postToChat: "Post this to the chat",
        keepUp: "You have successfully recognized your coworker.",
        catchErr: "Oops! something went wrong",
        closeWindowCatchErr: "You can close this window and retry later.",
        closeWindow: 'You can now close this window',
        allRecipients: 'All Recipients'
      },
      polls: {
        bannerHeader: "Listen to your team.",
        bannerDesc: "Collect and understand their feedback to create action plan that works.",
        startNewPoll: "Start a New Poll",
        newPoll: "Create a New Poll",
        pollTitle: "Poll Title",
        create: "Create",
        addChoices: "Add Choices",
        enterPollQuestion: "Enter Poll Question",
        pollQuestionTooltip: "Ask your poll question",
        choicePollTooltip: "Give choices for the audience to vote",
        closingPollTooltip: "Set poll end date to finalize the choices",
        poleTitleValidationMsg:"The poll question cannot be empty",
        invalidOption: "Invalid Option",
        pollOptionsValidationMsg: "The choice is repeated",
        pollChoiceValidationMsg: "Poll choices cannot be empty",
        minimumOptionsValidationMsg: "The poll question requires a minimum of 2 options.",
        choiceExceedMsg: "You have exceeded the maximum number of choices allowed",
        pollSuccessMsg: "Poll successfully created",
        dragTooltip:  "Drag up/down",
        multipleChoice:"Multiple Choice",
        singleChoice:"Single Choice",
        pollCloseOn: "Poll closes on",
        closingDate: "Closing Date",
        vote: "Vote",
        deletePoll: "Delete poll",
        copyLink: "Copy Link",
        pollDeletedMsg: "Poll successfully deleted",
        pollDeleteConfirmationMsg: "Are you sure you want to delete the poll?",
        new: "NEW",
        closed: "Closed",
        selectTeamMembers: "Select Team Members",
        selectRespondents: "Select Respondents",
        selectPollAudience: "Select Poll Audience",
        selectMembers: "Select Members",
        addMembers: "Add Members",
        publishPoll: "Publish Poll",
        clearMembersWarning: "All the selected members will be removed. Do you wish to clear all?",
        popupWarning: "You have made some changes to the list, do you wish to save?",
        selectPollAudienceWarning: "Please select poll audience",
        maxSixChoices: "Maximum 6 choices",
      },
      survey: {
        bannerHeader: "Get collective data! What Survey do you wish to do today?",
        bannerDesc: "Gain insights and research information from the world.",
        startNewSurvey: "Start a new Survey",
        newSurvey: "Create a New Survey",
        createNew: "Create New",
        savedTemplates: "Saved Templates",
        progress: "Progress",
        questions: "Questions",
        addMembers: "Add Members",
        saveAsTemaplate: 'Save as template',
        saveAndPublish: "Save and Publish",
        input: 'Input',
        surveyTitle: 'Survey Title',
        surveyCategory: 'Survey Category',
        description: 'Description',
        anonymousSurvey: 'Make survey responses anonymous',
        createQuestionnaire: 'Create Questionnaire',
        step1: 'Step 1',
        step2: 'Step 2',
        step3: 'Step 3',
        addQuestion: 'Add Question',
        addNextQuestion: 'Add next Question',
        maxTenQsns: 'Maximum 20 Questions',
        qsnPH: 'Type an open Question',
        addChoices: "Add Choices",
        multipleChoice:"Multiple Choice",
        singleChoice:"Single Choice",
        star: 'Star',
        smiles: 'Smiles',
        slider: 'Slider',
        minValue: 'Min Value',
        maxValue: 'Max Value',
        selSmilesVal: 'Select Rating Value',
        poor: 'Poor',
        okay: 'Okay',
        good: 'Good',
        addTeamMembers: 'Add Team Members',
        none: 'None',
        add: 'Add',
        selectTeamMembers: 'Select Team Members',
        sortByBu: 'Sort by Business unit',
        addParticipants: 'Add Participants',
        selectedTeamMembers: 'Selected Team Members',
        sortByBusinessUnit: 'Sort by Business Unit',
        selectAll: 'Select All',
        enterSurveyTitle: 'Enter Your Survey Title',
        questionErrMsg: 'Question cannot be empty',
        descriptionPH: 'Give more details to Participants',
        publishNow: 'Publish Now',
        surveyClosingDate: 'Survey Closing Date',
        setRemainder: 'Set Reminder',
        day: 'Day',
        time: 'Time',
        createAndPreview: 'Create your first question and get the Preview',
        shareYourSurvey: 'Share your survey with others',
        addOneOrMoreUsers: 'Add 1 or more users',
        saveMembersToTemp: 'Save Members To Template',
        allEmployess: 'All Employees',
        qsnsExceedMsg: "You have exceeded the maximum number of questions allowed",
        surveyDateValidationMsg: "(!) Exceeded - Reduce reminder day/s",
        templateCreationMsg: 'Template Saved Successfully',
        surveyCreationMsg: 'Survey Published Successfully',
        emptyValidation: 'Please enter Value',
        chooseSurvey: 'Choose Survey from saved templates',
        searchBySurveyName: 'Search by Survey Name',
        selCategory: 'Select Category',
        useThisSurvey: 'Use this Survey',
        addOther: 'Add "Other"',
        commentsFiled: 'Comments field will be added by default',
        removeQuestion: 'Remove Question',
        closingDate: "Closing Date",
        closed: "Survey Closed",
        participateInSurvey: "Participate in the survey",
        surveyNotAvailable:"Survey not available",
        new: "New",
        creator: "Creator",
        anonymousSurvey: "Anonymous Survey",
        allSurvey: "All Surveys",
        mySurvey: "My Surveys",
        enterDescription: "Enter your description here",
        viewAnswers: "View Survey Response",
        surveyModalBottomTxt: "All the Questions must be answered to submit survey",
        excellent: "Excellent",
        editCloseOption: "Edit closing date",
        lowSkilled: "Low skilled",
        highSkilled: "Highly skilled",
        answersSubmitted: "Answers submitted",
        surveySubmitted: "Survey is submitted successfully",
        avg: 'Avg',
        surveyResponses: 'Survey Responses',
        exportResult: 'Export Result',
        totalSurveyResponses: 'Total Survey Responses',
        rating: 'Rating',
        surveyReqParticipants: 'Did not participate',
        surveyRespParticipants: 'Participated',
        noAnswers: 'No Survey Responses Yet',
        adyRespondes: 'You have already responded to the survey',
        selectDate: 'Select date',
        selectTime: 'Select time',
        enableTime: 'Enable time',
        editAnswers: "Edit Answers",
        question: "Question",
        survey: "Survey",
        surveys:"Surveys",
        editTextInfo: "You can edit answers till the closing date",
        selectRespondents: "Select Respondents",
        selectSurveyAudience: "Select Survey Audience",
        suveyCompleted: "Survey Completed",
        surveyCancelled: 'Survey Cancelled',
        surveyCancel :'Are you sure, you want to cancel this survey?',
        surveyCanceldSuccess: 'This survey has been canceled',
        surveyCancelledEditAnswers: "Sorry, this survey has been cancelled.",
        surveyCancelledNotificationMessage:  "Sorry but this survey has been cancelled",
        AddLabels: "Add Labels", 
        EditLabels: "Edit Labels",
        matrix: "Matrix",
        rowLabel: "Row (Question)",
        colLabel: "Column (Answer)",
        matrixErr: 'Please add rows and columns',
        rowLabelMinError: 'Minimum rows allowed is 2',
        colLabelMinError: 'Minimum columns allowed is 2',
        preview: 'Preview',
        nonParticipantSurveyErr: "Thank you so much for being so interested, but you are not a participant in this survey.",
        ownerSurveyErr: "Thank you so much for being so interested, but the survey owner is not allowed to participate in this survey.",
        leftLabel: "Left Label",
        rightLabel: "Right Label",
        emptyRowColumn:"Row/column cannot be empty",
        searchSurvey:"Search by survey title and description",
        sentOn:"Published date",
        dueDate:"Due date",
        response:"Response",
        surveyTitle:"Survey title",
        surveyDescription:"Survey description",
        createdBy:"Created by",
        surveyee:"Surveyee",
        viewResponse:"View response",
        exportResult:"Export result",
        addParticipant:"Add participant",
        changeDueDate:"Change due date",
        allowCreatorParticipate:"Allow survey creator to participate",
        emptySurvey:`Hey! It looks like you have not created a survey yet. 
                        Start by creating a survey from the survey tab!`,
        searchByName:"Search by name"
        
  
  
      },
      newsFeed: {
        post: "Post",
        in:" in",
        imgPost:"posted an image",
        videoPost:"shared a video",
        docFeed:"posted a document",
        linkFeed:"shared a link",
        postFeed:"shared a post",
        sharePost: "Share a Post",
        goodMorning: "Good Morning!",
        goodAfternoon: "Good Afternoon!",
        goodEvening: "Good Evening!",
        sharePostPlaceholder: "What do you wish to share now?",
        noFeedsAvailable: "No feeds available!",
        warning: "You will lose your data. Are you sure you want to cancel?",
        wcMsg: "Hi, ", 
        seeMore: "...see more",
        seeLess: "...see less",
        addComment: "Add a comment",     
        appreciate: "Appreciate", 
        comments: "Comments",
        reply: "Reply",
        replies: "Replies",
        like: "Like",
        likes: "Likes",
        replyComment: "Reply to the comment",  
        loadMoreComments: "Load more comments",
        deletePost: "Delete Post",
        pinpost: "Pin Post",
        unpinpost: "Unpin Post",
        reportPost: "Report Post",
        copyLink: "Copy Link",
        feedDeleteConfirmationMsg: "Are you sure that you want to delete this post?",
        commentDeleteConfirmationMsg: "Are you sure you want to delete the comment?",
        replyDeleteConfirmationMsg: "Are you sure you want to delete the reply?",
        feedDeletedMsg: "Feed successfully deleted",
        commentDeletedMsg: "Comment successfully deleted",
        replyDeletedMsg: "Reply successfully deleted",
        loadMoreReplies: "Load more replies",
        pinpostFeedMsg: "Do you want to pin this post?",
        unpinpostFeedMsg: "Do you want to unpin this post?",
        reportpostFeedMsg: "Do you want to report this post?",
        reportFeedSuccMsg: "Post has been reported successfully!",
        hashtagHeader: "Here is the post related to",
        share: "Share",
        hidepin: "Hide Pinned Post",
        viewPinnedPost: "View pinned posts",
        editPost: "Edit post",
        editPostBtn: "Edit Post",
        feedPlaceholder : "Write here or use @ to mention someone.",
        createPost: "Create a Post",
        maxPhotoMsg: "Photos exceed the maximum upload limit of 20",
        author: "Author",
        deleteFeed: "Yes, Delete",
        confirmation: "Confirmation",
        peopleLikeThis: "People who like this",
        commentValidationMsg: "Please enter a comment before sending",
        replyValidationMsg: "Please put comment before sending",
        comment: "Comment",
        noonePosted: "Looks like no one posted anything here yet.",
        nopreview: "(preview is not supported)",
        nothingShow:"Nothing to show",
        newsFeed: "Newsfeed",
        communityFeed: "Show Community feed only"
        },
      common: {
        close: "Close",
        signOut: "Sign Out",
        cancel: "Cancel",
        discardChanges: "Discard Changes",
        saveChanges: "Save Changes",
        search: "Search",
        confirm: "Confirm",
        upload: "Upload",
        save: "Save",
        ok: "OK",
        name: 'Name',
        address: 'Address',
        phone: 'Phone',
        email: 'Email',
        submit:"Submit",
        next: "Next",
        add: 'Add',
        dismiss: 'Dismiss',
        chat: 'Chat',
        settings: 'Settings',
        delete: "Delete", 
        description: "Description",
        back: "Back",
        notAvailable: "Not available.",
        edit:"Edit",
        set: "Set",
        all: "All",
        everyone:"Everyone",
        individuals: "Individuals",
        groups: "Groups",
        bussinessUnits: "Business units",
        clearAll: "Clear all",
        individualPlaceholder:"Search by Individual name",
        businessUnitPlaceholder: "Search by Business unit name",
        noUserFound: "No user found!",
        selectAnyOption: "Select any one option from the dropdown",
        update: "Update",
        imageWarningMessage: "This file format is not supported. Please upload only jpeg, jpg, png or gif images",
        yes: "Yes",
        no: "No",
        more: "More...",
        authenticationError: "authentication token is expired or not valid",
        internalErr: "Something went wrong, please try again later.",
        addRow: "Add Row",
        addColumn: "Add Column",
        warning: "Do you want to discard your changes?",
        confirmationPopupHeader: "Your action is not completed",
        discard: "Discard",
        continueToEdit: "Continue to edit",
        send: "Send",
        warning: "You will lose your data. Are you sure you want to cancel?",
        help: 'Help',
        reqDemo: 'Request for a demo',
        emailSupport: 'Email Support',
        fileWarning: 'Please upload valid file.',
        fileSizeValidation: "File size must not exceed 1 GB!",
        documentfileSizeValidation: "File size must not exceed 100 MB!",
        validateUrl: "Please enter valid URL"
      },
      mib: {
        menu: "Message in a bottle"
      },
      reportIssue: {
        headerTitle: "Have an issue? Let us know",
        whereIsProblem: "Where is the problem?",
        whatWentWrong: "What went wrong?",
        whatWentWrongPlaceholder: "Briefly explain what happened and what steps we can take to reproduce the problem",
        uploadFiles: "Upload Files",
        uploadFileDesc: "Browse or upload your file here",
        selectFeature: "Select the feature",
        fileValidationMsg: "You're not allowed to attach more than 5 files into a report",
        fileFormatValidationMsg: "This file format is not supported.",
        reportIssueConfirmationHeader: "Are you sure you want to report this issue?",
        reportIssueConfirmationSubheader: "You will not be able to undo it once sent",
        uploadingAttachmentMsg: "Please wait while we upload your attachment(s)...",
        uploadAttachments: "Uploading attachment(s)",
        thankYou: "Thank you",
        successMsg: "Your issue has been submitted. We may reach out to you if we need more information. "
      }
  }
  export default en;